name: Build and Package LuaJIT

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    uses: ./.github/workflows/build-windows.yml
  
  package-zip:
    needs: build
    uses: ./.github/workflows/package-zip.yml
  
  package-msi:
    needs: build
    uses: ./.github/workflows/package-msi.yml
  